#ifndef _OBJECTS_H_
#define _OBJECTS_H_

enum {
    CC2_TYPE_GRAPPLE_PICKUP = 20,
    CC2_TYPE_SPIKE_V = 36,
    CC2_TYPE_SPIKE_H = 37,
    CC2_TYPE_SNOWBALL = 62,
    CC2_TYPE_SPRINGBOARD = 11,
    CC2_TYPE_GRAPPLER = 46,
    CC2_TYPE_BRIDGE = 63,
    CC2_TYPE_BERRY = 21,
    CC2_TYPE_CRUMBLE = 19,
    CC2_TYPE_CHECKPOINT = 13,
    CC2_TYPE_SNOWBALL_SPAWNER_R = 14,
    CC2_TYPE_SNOWBALL_SPAWNER_L = 15,
    CC2_TYPE_PLAYER = 2
};

#endif